export enum Permission {
  // Teacher permissions
  UPLOAD_PDF = 'UPLOAD_PDF',
  GENERATE_QUESTIONS = 'GENERATE_QUESTIONS',
  EDIT_QUESTIONS = 'EDIT_QUESTIONS',
  EXPORT_JSON = 'EXPORT_JSON',

  // HOD permissions
  REVIEW_QUESTION_SETS = 'REVIEW_QUESTION_SETS',
  APPROVE_QUESTION_SETS = 'APPROVE_QUESTION_SETS',
  REJECT_QUESTION_SETS = 'REJECT_QUESTION_SETS',

  // Principal permissions
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',

  // Student permissions
  VIEW_ASSESSMENT = 'VIEW_ASSESSMENT',
}
